### ISSUE TITLE
Questions regarding -a option and unique mapping

### ISSUE THREAD

**Issue by JunxiFeng** [smithlabcode/abismal#10]
Hello,

I have 2 quick questions:

1) For the -a option, how is the sensitivity defined here?

2) I notice that the -s option can output the mapping statistics, which seems to include # of uniquely mapped reads, I am just curious about how the # of uniquely mapped reads is counted.

Thanks a lot!!

**Comment by guilhermesena1** [comment]
Hello, and thank you for reaching out with the question.

The `-a` option will output both reads that map uniquely and ambiguously to the SAM output, with ambiguous reads identifiable by the bit 0x100 in the SAM flags. Ambiguous reads will have a randomly selected mapping location among the highest scoring locations, so be careful with any downstream methylation quantification for the CpGs the reads map to (it is fine to use amibguous reads for some global summary statistics like bisulfite conversion, though). 

In single-end read mapping with the `-a` flag, the number of SAM entries should be equal to the number of reads reported in the `num_mapped:` field in the map statistics. If `-a` is not set, then the number of lines must be equal to the `num_unique:` field, so for instance, doing
```
samtools view out.sam | wc -l
```
should output the same number as one of the other (depending on whether or not `-a` is used).

The reads that are reported as "mapped" are the ones whose edit distance to the reference genome, relative to the mapped portion, is less than the fraction set by the `-m` flag. By default `m` is set to 0.1, meaning that reads will be considered "mapped" if at least 90% of the read bases are matches to its mapping location. Reads that do not cross this cut-off are not reported, but summarized in the `num_unmapped:` field in the map statistics.

More on the "options" section in the [documentation](https://github.com/smithlabcode/abismal/blob/master/docs/MANUAL.md)

Hope this clarifies your question!

**Comment by guilhermesena1** [comment]
I'll be closing this from inactivity, but please feel free to re-open if there are additional questions!
