### ISSUE TITLE
git clone fails on src/smithlab_cpp

### ISSUE THREAD

**Issue by john-dtu** [smithlabcode/abismal#11]
Using git version 2.4.4. 
git clone --recursive git@github.com:smithlabcode/abismal.git
Cloning into 'abismal'...
remote: Enumerating objects: 1535, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 1535 (delta 95), reused 90 (delta 56), pack-reused 1396
Receiving objects: 100% (1535/1535), 485.28 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1096/1096), done.
Checking connectivity... done.
Submodule 'src/smithlab_cpp' (git@github.com:smithlabcode/smithlab_cpp.git) registered for path 'src/smithlab_cpp'
Cloning into 'src/smithlab_cpp'...
remote: Enumerating objects: 2850, done.
remote: Counting objects: 100% (208/208), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 2850 (delta 119), reused 207 (delta 118), pack-reused 2642
Receiving objects: 100% (2850/2850), 1.28 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1592/1592), done.
Checking connectivity... done.
fatal: reference is not a tree: c7e1386216c82e33ed0e3def57ff87634db0121c
Unable to checkout 'c7e1386216c82e33ed0e3def57ff87634db0121c' in submodule path 'src/smithlab_cpp'

**Comment by john-dtu** [comment]
Thanks, would it be possible to have a clearer information about version? 
Preferably on the front page. It would make it so much easier for maintainers for software repositories.
Seems like we are a 3.0.0 or ???

**Comment by guilhermesena1** [comment]
Yes we are at 3.0.0. Stable releases are tracked in the [releases page](https://github.com/smithlabcode/abismal/releases) and in the [quick installation](https://github.com/smithlabcode/abismal/blob/master/docs/MANUAL.md#quick-installation) section on the manual. We use the README for a general description of the program that does not depend on the release.

**Comment by john-dtu** [comment]
Thanks for the clarification
