### ISSUE TITLE
More info among verbose output

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/abismal#13]
It might be very helpful to have the verbose output report the number of threads used.

**Comment by guilhermesena1** [comment]
I added this info on 7074f0e . However, I was trying to handle cases where the number of threads used is not the same as the number of threads requested. Seems like `omp_get_num_threads()` returns the number of threads requested nonetheless. In the meantime I added a warning if `omp_get_num_threads() > omp_get_num_procs()`, and just printed the number of threads requested in verbose
