### ISSUE TITLE
Unable to install from release download

### ISSUE THREAD

**Issue by cawa78** [smithlabcode/abismal#15]
Hi,
I tried installing from the release download on a Mac with an M1 chip and when I try $ make all, I get an error: 

src/abismal.cpp:38:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make[2]: *** [src/abismal.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Someone else tried running this on a Mac with an intel chip and got the same error. Is there anything we can try?

**Comment by andrewdavidsmith** [comment]
Can you most the output from running the configure script?

**Comment by cawa78** [comment]
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking whether g++ supports C++11 features with -std=c++11... yes
checking for ranlib... ranlib
checking for g++ -std=c++11 option to support OpenMP... unsupported
checking for zlibVersion in -lz... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
=== configuring in src/smithlab_cpp (/Users/carriewalls/abismal/abismal-3.0.0/src/smithlab_cpp)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/Users/carriewalls/abismal'  --cache-file=/dev/null --srcdir=.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking whether g++ supports C++11 features with -std=c++11... yes
checking for gcc... gcc
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for ranlib... ranlib
checking for zlibVersion in -lz... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands

**Comment by guilhermesena1** [comment]
Hello,

Thanks for sharing the issue with us. My best guess is your default C++ compiler is clang++? (e.g. if you do `which g++`). I've seen this issue before as OpenMP is not natively included in clang's libs on OSX.

One possible solution would be to run
```
brew install libomp
```

another one, if you have GNU g++ (e.g. in `/usr/bin/g++` or `/usr/local/bin/g++`) is to use that for compilation, but I too will need a macbook to try and reproduce this. Sorry for the inconvenience!

**Comment by cawa78** [comment]
I tried running $ brew install libomp and get the following error: 

 "_omp_set_num_threads", referenced from:
      _main in abismal.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [abismal] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

I know that g++ is located in /usr/bin/g++ on my machine, but I don't know how to instruct autotools to use it over clang.

**Comment by guilhermesena1** [comment]
got it! I can reproduce all the errors mentioned above, we're trying to figure out the easiest solution to compile it successfully.

In the meantime, just to try and make this compile for you, here's what worked for me 

(1) install llvm and automake
```
$ brew install llvm automake
```

(2) Change line 28 the `Makefile.am` file from
```
LDADD = src/smithlab_cpp/libsmithlab_cpp.a
```

to
```
LDADD = src/smithlab_cpp/libsmithlab_cpp.a -lomp
```

(3) run the following
```
$ autoreconf -i
```

(4) finally, try running `./configure` and `make` as you ran beforehand, with whichever flags you added.

This is definitely not how it's supposed to be, and we need to find the proper way to handle GNU/clang++ through autotools, but hopefully in the short term this may help.

Sorry again for the inconvenience!

**Comment by cawa78** [comment]
Thanks for the fix! After $ autoreconf -i,  I edited the Makefile and added the lines:

CC=clang++
FLAGS=-g -Wall -std=c++17 -arch arm64 -lomp
LDFLAGS=-L/opt/homebrew/lib
CPPFLAGS=-I/opt/homebrew/include

Then I ran $ make all and it worked.

**Comment by guilhermesena1** [comment]
Glad it worked! I'm also drafting a release to fix this issue generally.

Just a side note: be careful adding the `-g` flag to `FLAGS`, this may compile the problem in debug mode, which will likely make it much much slower! I'd replace `-g` by `-O3` for fastest performance :)
