### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Hannah1746** [smithlabcode/abismal#5]
I am trying to use methpipe and can't seem to get it to work for me.

I first run:
abismalidx FINAL_MX_HiC_50CHRs_rn.fa MX.abismalidx

This produces an index file that is  2.7G from my 2.3G genome

Then I run:
abismal -i MX.abismalidx -o MX_gill.sam MX_gill_output.fastq
but I get this core dumped error so I tried:
abismal -g FINAL_MX_HiC_50CHRs_rn.fa -o MX_gill.sam MX_gill.fastq
I get the same error on this too. 

I am using Nanopore data so my fastq are singled end and are all cated together.

**Comment by guilhermesena1** [comment]
closing this issue for now (this was incorporated on 2.0.0) but feel free to reopen if this problem resurfaces.
