### ISSUE TITLE
bad reads file (but it looks good to me) 

### ISSUE THREAD

**Issue by karl1926** [smithlabcode/abismal#6]
Hi guilhermesena1,
we already talked on the WALT page because I was having problem with the index. As you suggested I tried abismal and the index worked fine. But Now I am having problems mapping. The sam file only contain the header. the -V option prints the following error about bad reads file:

src/abismal -i ../../data/genomes/Homo_sapiens.GRCh38.dna.primary_assembly.abismalidx -o ../../local_storage/output.sam ../../data/prostate/SRA/input_1.fastq -t 6 -V
bad reads file: -V

My fastq file (single end) looks fine to me. Maybe short reads are not supported?

My fastq head:
@SRR8633966.1 1 length=29
TGGGTTTGATTTGAGGAGAATTGTGTTTC
+SRR8633966.1 1 length=29
BBCFDDFFHHHHHIJJIJJJJJJEHHIJJ
@SRR8633966.2 2 length=29
TGGGTTTGATTTGAGGAGAATTGTGTTTC
+SRR8633966.2 2 length=29
CCCFFFFFDHHHHHIFHIGEHHGEHFFHD
@SRR8633966.3 3 length=29
TGGGTTTGATTTGAGGAGAATTGTGTTTC
+SRR8633966.3 3 length=29
BBCFBDFFHHHHHHJJJJIJJJIHIGIJJ
@SRR8633966.4 4 length=29
TGGGTTTGATTTGAGGAGAATTGTGTTTC

**Comment by guilhermesena1** [comment]
Hi,

Thanks for reaching out about the issue. The read file has to be the last parameter in the command, and the verbose option is a lowercase v (`-v`), so the correct command would be like this

```
src/abismal -i ../../data/genomes/Homo_sapiens.GRCh38.dna.primary_assembly.abismalidx -o ../../local_storage/output.sam  -t 6 -v ../../data/prostate/SRA/input_1.fastq
```

Hope that helps!

**Comment by karl1926** [comment]
Hi guilhermesena1,
thanks for the quick reply! I tried your suggestion but, while I got a proper log print, the sam output remains the same. Very small size and only header.
This is what the -v option returns:

src/abismal -i ../../data/genomes/Homo_sapiens.GRCh38.dna.primary_assembly.abismalidx -o ../../local_storage/output.sam -t 6 -v ../../data/prostate/SRA/input_1.fastq 
[Mon Dec  6 17:30:56 2021] input (SE): ../../data/prostate/SRA/LNCaP_WGBS_SRR8633966_1.fastq
[Mon Dec  6 17:30:56 2021] output (SAM): ../../local_storage/LNCaP_WGBS.sam
[Mon Dec  6 17:30:56 2021] loading index ../../data/genomes/Homo_sapiens.GRCh38.dna.primary_assembly.abismalidx
[Mon Dec  6 17:31:18 2021] loading time: 21.298532s
[calculating mapping parameters from index]
[mapping reads|===================================================|100%]


Any idea?

**Comment by guilhermesena1** [comment]
can you add `-s output.stats` to your command to generate a mapping statistics file and paste the output of this file here? I believe it's going to show that all reads are skipped. I just noticed that their length is 29 bp, which is below the minimum length of 35 needed to get at least one seed.

**Comment by karl1926** [comment]
Hi guilhermesena1,
I guess you were right, all reads are skipped. 

total_reads: 196267817
mapped: 
    num_mapped: 0
    num_unique: 0
    num_ambiguous: 0
    percent_mapped: 0
    percent_unique: 0
    percent_ambiguous: 0
    unique_error:
        edits: 0
        total_bases: 0
        error_rate: 0
num_unmapped: 196267817
num_skipped: 196267817
percent_unmapped: 100
percent_skipped: 100


can you tell me if walt also works with a minimum read length of 35 bp_

best

karl

**Comment by andrewdavidsmith** [comment]
There is now (since 34af2347df7086b8d05a2c63728740456e0bf242) an option to build `abismal` and `abismalidx` to handle very short reads. The configure script has the following option:
```
 --enable-short          optimize for very short reads [no]
```
When used, abismal will be much more sensitive and able to map reads of length 36 or longer, but at some cost to speed. The default build maps reads of length 44 or longer.
