### ISSUE TITLE
Problem with "make all"

### ISSUE THREAD

**Issue by kevinmcnaught** [smithlabcode/abismal#8]
Received this error message during "make all" command:

src/AbismalIndex.cpp:31:10: fatal error: 'parallel/algorithm' file not found

Any thoughts?

**Comment by guilhermesena1** [comment]
Hi,

Thanks for bringing this issue to our attention. Could you confirm which operating system you are trying to install abismal on, as well as the g++ version (clang/gnu c++)? Thank you!

**Comment by guilhermesena1** [comment]
I'll be closing these because we recently got rid of `parallel/algorithm`, but please feel free to re-open if you are still having issues!
