### ISSUE TITLE
FYI -- VERBOSE parameter 

### ISSUE THREAD

**Issue by vagan21** [smithlabcode/abismal#9]
Hello,

I wanted to let you know that when you do `abismal --help `in the terminal, the VERBOSE flag (-v) is listed as being LOWERcase, whereas on your GitHub, it is listed as UPPERcase. Initially I was unable to map because I had `abismal -V -t 8 -i index read1.fq read2.fq`...then I realized the program was not able to recognize the -V parameter. Once I changed it to -v, it worked. Just an FYI that this mistake should be fixed on the Git site. Right now, to me, it looks uppercase instead of lowercase on the Git site.

Verda Agan 

How it looks in terminal: 

```
Usage: abismal [OPTIONS] <reads-fq1> [<reads-fq2>]

Options:
  -i, -index         index file -o 
  -g, -genome        genome file (FASTA)  
  -o, -outfile       output file (SAM) [stdout]  
  -s, -stats         map statistics file (YAML)  
  -x, -sensitive     run abismal in sensitive mode  
  -t, -threads       number of threads [1] 
  -l, -min-frag      min fragment size (pe mode) [32] 
  -L, -max-frag      max fragment size (pe mode) [3000] 
  -m, -max-distance  max fractional edit distance [0.100000] 
  -a, -ambig         report a posn for ambiguous mappers  
  -P, -pbat          input follows the PBAT protocol  
  -R, -random-pbat   input follows random PBAT protocol  
  -A, -a-rich        indicates reads are a-rich (se mode)  
  -v, -verbose       print more run info  
```

How it looks on your website: 

![Screen Shot 2022-01-31 at 4 41 40 PM](https://user-images.githubusercontent.com/75225141/151885139-5c5af3e5-d7d9-40ac-92e7-104eafc50b95.png)

**Comment by guilhermesena1** [comment]
Thank you so much for reporting this! The README front page was indeed in dire need of updates on the available parameters. I pushed commit 4bd64fe which makes the parameters consistent with the `--help` page. Apologies for the confusion!
